apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sql
  name: sql-pv-claim
  namespace: eman-tawazun
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi