apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: eman-tawazun
  labels:
    app: db-service
spec:
  type: ClusterIP
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:  
    app: sql 