apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: eman-tawazun
  labels: 
    name: eman
spec:
  selector:
    app: deploy
  ports:
    - port: 80 
      targetPort: 8080
  type: LoadBalancer  